### ISSUE TITLE
Improve run directory (output management)

### ISSUE THREAD

**Issue by hboisgon** [Deltares/Wflow.jl#100]
When doing several runs of wflow for the same model, it is a bit long to set up and keep track of the output (example using different forcing, run with/without reservoir, updating model parameters...).

It could be nice to again have (like in the python version) an option to setup an output directory:
 - this avoids having to change [states] path_output + [output] path + [csv] path options in the toml for each new run (create a common path output argument and just edit the name of the file)
 - in this directory, a copy of the toml file can be added to keep track of the options used for this run
 - additionnally a .log file to keep track of what happened during the run can be added.

**Comment by verseve** [comment]
This is indeed not possible with the wflow exe. You can redirect stdout to a file, e.g.:
```
wflow_cli config.toml > log.txt
```

In addition it is probably good to know that you can change the Config object on the fly quite easy, for example to set/change the output NetCDF file:

```julia
using Wflow

config = Wflow.Config(tomlpath)
config.output.path = "data/run01-moselle.nc"
```

**Comment by visr** [comment]
There is indeed no single output directory, but the output files can be given a path separately. This provides more flexibility, though as you say if you want to redirect output to a different directory, that requires edits to ~3 paths in the TOML. However, perhaps a slightly different workflow can give the same effect. One that takes into account that relative paths are relative to the TOML file.

Consider a file tree like this:
```
project
│   input.nc
│
└─── with_reservoir
│   config.toml
│   output.nc
│   
└─── without_reservoir
│   config.toml
│   output.nc
```

In the TOML you can refer to the parent directory to find the input, and write the output besides the TOML (or a subfolder). This way you don't need to modify the paths in the TOML, a copy of the TOML stays with the run, and by redirecting output as mentioned above you can store the log.txt as well. Would such an approach work for you as well?

**Comment by hboisgon** [comment]
Thanks for your answer. And yes I started doing this approach indeed, creating a new folder and then copy-pasting a template TOML that is then edited. Still some manual steps compared to wflow python but you can track a bit better which settings where done for each run.

However if you want to quickly change a parameter value using Willem's trick (multiply parameter between model initialization and run) then you loose the fact that the toml registers your run and for multiple parameter multiplication, then I just end up with the same template toml file and use a run_wflow.jl script to first change the output path after reading the toml and then change the parameters before runnning the model. So again loosing track of what was done (no toml copy or log file with all options used).

`using Wflow

tomlpath = (raw"C:\Users\boisgont\D\Drive\Japan\wflow_Tenryu\sbm_mswep.toml")

# TT 1.5
config = Wflow.Config(tomlpath)
config.output.path = "calib_runs/param_change/TT-1p5/output.nc"
config.csv.path = "calib_runs/param_change/TT-1p5/output.csv"

model = Wflow.initialize_sbm_model(config)
model.vertical.tt .= 1.5 .+ model.vertical.tt
Wflow.run(model)`

**Comment by visr** [comment]
> However if you want to quickly change a parameter value using Willem's trick (multiply parameter between model initialization and run) then you loose the fact that the toml registers your run and for multiple parameter multiplication

Yes indeed. Although technically you can do anything to the model from julia, including things that cannot be captured in the TOML, so it is hard to solve this in general. This is partly also #101, but yesterday I discussed with Willem that perhaps we should solve that by including a new section in the TOML that lets you modify any input parameter. Then these kind of modifications are also captured there.

**Comment by hboisgon** [comment]
That would be really great!
