### ISSUE TITLE
Improve model parameters update (old -P option)

### ISSUE THREAD

**Issue by hboisgon** [Deltares/Wflow.jl#101]
For fast sensitivity analysis of the model, it could be nice to add a multiplier option of model parameters before starting the wflow run. This used to be the -P option in wflow python.

As of now the manual process to replace this option implies creating the multiplied parameter map + adding it to staticmaps.nc + edits in the toml file (new parameter name + edit of the outputs path).

**Comment by verseve** [comment]
With the wflow exe this is indeed not possible. Please note that you can change model parameters after initialization of the the model, for example:

```julia
using Wflow

config = Wflow.Config(tomlpath)
model = Wflow.initialize_sbm_model(config)
model.vertical.soilthickness .= 2.0 .* model.vertical.soilthickness
Wflow,run(model)
```

Also there is the BasicModelInterface.

**Comment by hboisgon** [comment]
The above solution does not work for ksathorfrac parameter as it is not directly part of LateralSSF struct:
model.lateral.subsurface.ksathorfrac .= 0.1 .* model.lateral.subsurface.ksathorfrac

Multiplying directly the horizontal conductivity gives an error:
model.lateral.subsurface.kh₀ = 0.1 .* model.lateral.subsurface.kh₀

ERROR: LoadError: setfield! immutable struct of type LateralSSF cannot be changed

**Comment by verseve** [comment]
It works, but you did forget the "." in front to the equal sign "=":

```julia 
model.lateral.subsurface.kh₀ .= 0.1 .* model.lateral.subsurface.kh₀
```

**Comment by laurenebouaziz** [comment]
the above works for me.

I tested:
model.lateral.land.n .= 2 .* model.lateral.land.n
and
model.lateral.river.n .= 2 .* model.lateral.river.n

it both runs without giving an error, but it gives exactly the same output as the run without the multiplication.
any idea what goes wrong?

**Comment by visr** [comment]
Hmm looking at the code here: https://github.com/Deltares/Wflow.jl/blob/b3fadf2cdd0079998cbffa1bacdad7e2cb234fd7/src/sbm_model.jl#L157-L175

I see that the `n` is used to calculate `α` during model initialization, and it seems that `n` is not directly used afterwards anymore. So your update worked, but is not seen anymore by the simulation code.

These interdependent parameters can be quite confusing. Maybe @verseve has an idea what we should do here. Recalculate `α` every timestep? It's not great to have `n` in the struct now, and it not being used.

**Comment by laurenebouaziz** [comment]
another related issue that I just discussed with Willem:

if a multiplication is applied to theta_s parameter after initializing the model: 
model.vertical.θₛ .= 0.99 .* model.vertical.θₛ
this won't affect the calculation of θₑ = θₛ .- θᵣ (also in the initialization)
subsequently I think theta_s is mostly used in the vertical processes, however theta_e is passed on the lateral processes (therefore without multiplication). 

this explains some very strange results I obtained earlier with a multiplication of theta_s*0.99

this is related to the n issue discussed before.

**Comment by verseve** [comment]
Yes indeed, good point @visr , the `n` (Manning's n) parameter is not part of calculations during the simulation (update). On the other hand for most hydrologists/modelers this parameter is easier to interpret than `α`. We could also set the `alpha_term` in the struct to solve the parameter interdependence :

```julia
@get_units @with_kw struct SurfaceFlow{T,R,L}
alpha_term::Vector{T} = pow.(n ./ sqrt.(sl), β)
```

and we should probably do this then also for `α`. Or indeed include `n` in the calculation at every time step a you did suggest. Do you have a preference?

@laurenebouaziz : I think the solution with the `θₛ` issue is to explicitly link `sbm.θₛ` and `sbm.θᵣ` to the lateral subsurface struct.
