### ISSUE TITLE
Create Dockerfile and host image publically

### ISSUE THREAD

**Issue by evetion** [Deltares/Wflow.jl#109]
Maybe as a julia tag on the current [Wflow](https://hub.docker.com/repository/docker/deltares/wflow) image?

**Comment by visr** [comment]
What would you want the Docker to contain? The main entry point is the wflow_cli app, for which a tarball can be downloaded from https://download.deltares.nl/en/download/wflow/. Is that enough? Or if you need a Julia REPL, I guess we should take the julia docker, and use PackageCompiler.jl to bake Wflow.jl into the system image for fast startup.

**Comment by evetion** [comment]
I don't need the REPL, I would just like to start the model from the commandline. So that's the cli app I guess? PackageCompiler.jl could be nice, but not a hard requirement I'd say.

**Comment by visr** [comment]
Ok yes in most cases the cli app would be sufficient, and easiest. Not sure what the best practices are for throwing a generic linux tarball into a Docker container, but that's all that needs to happen.

**Comment by evetion** [comment]
Manual tryout. It now runs the test toml found in the documentation from /data. You can mount your own data and the cmd takes the location of the toml file:
```docker
ENTRYPOINT [ "/opt/wflow_cli/bin/wflow_cli" ]
CMD ["/data/sbm_simple.toml"]
```

Now available for public testing:

```julia
❯ docker run deltares/wflow:julia
┌ Info: Run information
│   model_type = "sbm"
│   starttime = CFTime.DateTimeStandard(2000-01-01T00:00:00)
│   Δt = 86400 seconds
└   endtime = CFTime.DateTimeStandard(2000-01-10T00:00:00)
Progress:   0%|                                         |  ETA: N/A
Progress:  10%|████▏                                    |  ETA: 0:00:14
Progress:  20%|████████▎                                |  ETA: 0:00:07
Progress:  30%|████████████▎                            |  ETA: 0:00:05
Progress:  40%|████████████████▍                        |  ETA: 0:00:04
Progress:  50%|████████████████████▌                    |  ETA: 0:00:03
Progress:  60%|████████████████████████▋                |  ETA: 0:00:02
Progress:  70%|████████████████████████████▊            |  ETA: 0:00:01
Progress:  80%|████████████████████████████████▊        |  ETA: 0:00:01
Progress:  90%|████████████████████████████████████▉    |  ETA: 0:00:00
Progress: 100%|█████████████████████████████████████████| Time: 0:00:04
Progress: 100%|█████████████████████████████████████████| Time: 0:00:04
```

**Comment by verseve** [comment]
Nice! @Pieter9011 could you test this?

**Comment by verseve** [comment]
Suggest to use `config.toml` for the TOML file. Or as argument to the docker if this is possible?

**Comment by evetion** [comment]
You can pass the _location_ of the toml file on the command line. You'd still have to mount a data directory with said toml and data next it, correctly referenced.

So if you've got a localdata directory with data and a `.toml`:

`docker -v localdata:/data deltares/wflow:julia /data/config.toml`

**Comment by JoostBuitink** [comment]
Thanks again for picking this up @evetion!

It would also be really nice if previous versions of wflow remain accessible through their version as a tag (so `wflow:v0.6.3` for example). Is it possible that every release gets two tags (`latest` and `v0.7.1`, for example)? This way `latest` always refers to the latest version, and you can use the version number to get a specific (older) version of Wflow. This is something that needs to be done in TeamCity I guess, right?

**Comment by evetion** [comment]
Sure, but Teamcity looks to the git repo for tags, and for https://gitlab.com/deltares/wflow/wflow_cli/-/tags, there are none.

I propose to merge the wflow_cli repo here, so we can make use of the releases (and thus tags) made here.

**Comment by JoostBuitink** [comment]
Ah right, that makes sense! We are indeed planning to merge the wflow_cli repo to here, so lets do that first!

**Comment by evetion** [comment]
I'm happy to update TC afterwards 👍🏻

**Comment by JoostBuitink** [comment]
That would be great! I have added the wflow_cli code to this branch https://github.com/Deltares/Wflow.jl/tree/merge_cli. Is there anything else that needs to be added? I see that in Ribasim.jl you have a .teamcity folder, I assume we need something like this as well?

**Comment by visr** [comment]
Probably best to discuss in #274 or a separate PR. I think it's worth it to copy as much as possibly, e.g. also the `build/create_binaries` folder, since it will make it easier to create libwflow once we'll start coupling.

Regarding the .teamcity folder, syncing TeamCity settings to the repo can be enabled from the TeamCity side, so no need to do that in your branch.
