### ISSUE TITLE
add an overview of model variables to documentation

### ISSUE THREAD

**Issue by ctenvelden** [Deltares/Wflow.jl#132]
It would be good to include an overview of model variables (names + explanation) in the documentation.

**Comment by visr** [comment]
> The documentation provides a mapping from model struct to the different component

This part is probably mostly interesting for developers. Users don't necessarily need to know how we represent things in structs.

For users it would be nice to see if we can generate such a table:

parameter | description | unit | default
-- | -- | -- | --
cfmax | Degree-day factor   for snow | mm ᵒC-1 Δt-1 | 3.75653

Ideally without duplicating this in code and docs, but generating this from the code or a TOML for instance.
