### ISSUE TITLE
Documentation that Describes Extracting and  Using Results

### ISSUE THREAD

**Issue by RudyFrom3** [Deltares/Wflow.jl#148]
I have been looking into this project for some time, but have struggled to find any good documentation that describes how to view and extract results. Can any one please direct me to where and how results are stored, and viewable and reportable ?

**Comment by visr** [comment]
Hi, thanks for the issue. Indeed I plan to add some example code of how results can be viewed and analyzed.

The output options in general are described from here: https://deltares.github.io/Wflow.jl/dev/config/#Output-NetCDF-section
So there is the option to either output the full grid for each timestep to netCDF, or to output timeseries to either netCDF or CSV.

How you wish to process the results also depends on your own preferences. If you wish to do so in Julia, you could have a look at https://github.com/rafaqz/GeoData.jl. In Python, http://xarray.pydata.org/en/stable/ is very convenient for analyzing netCDF data. But they can also be viewed in software like QGIS or Panoply.

**Comment by RudyFrom3** [comment]
Thankyou, Can you please describe opening the Files in QGIS ? Which files can be opened and what can be extracted via QGIS? Is there any plans to build Tools for this model in QGIS ?

**Comment by RudyFrom3** [comment]
I am in the following Position. I am a Technical Officer of a Local Government in Australia, and have the task to review the results submitted by a Consultant Using this Model. My problem is that So far, I am struggling to find a description of what is in the Output files, and how to view/extract the results.  Any guidance and advice would be much appreciated.

**Comment by visr** [comment]
> any plans to build Tools for this model in QGIS

There are no concrete plans at this point. We use standard file formats like netCDF and CSV such that users can use pre- and postprocessing tools of their choice. The netCDF files can already be just dragged into QGIS and they will show the information inside. Only the time support for netCDF rasters in QGIS is currently still minimal ([it needs scripting](https://www.geodose.com/2021/03/netcdf-temporal-visualization-qgis.html)), though you can select timesteps as bands in the raster.

To be able to slide through the timesteps, you can also load the netCDF as a Mesh layer (layer > add layer > add mesh layer), and enable the Temporal Controller. See https://docs.qgis.org/3.16/en/docs/user_manual/working_with_mesh/mesh_properties.html and https://www.lutraconsulting.co.uk/blog/2019/08/26/foss4g-workshop/.

> review the results submitted by a Consultant Using this Model

Perhaps it would be good if the consultant could postprocess the results, make graphs, compare to observations, such that the results are ready to analyze. Though for the CSV time series, which are often created at gauges, you could also open in software like Excel and review the results.
