### ISSUE TITLE
Custom run logic (anywhere)

### ISSUE THREAD

**Issue by Huite** [Deltares/Wflow.jl#169]
This is something that came up while discussing shuffling the forcing input around, with @hboisgon. In this use case, we'd like to do randomized runs; the randomized runs consist of a single meteorological forcing dataset, but the timesteps load different values (e.g. first run loads the forcing of year 2001 for simulation year 1951; the second run loads the forcing of year 2005 for year 1951, etc.). This has the obvious benefit of not having to generate enormous amounts of input. The most obvious way to implement this would be:

* Replacing the `get_at` function which takes a dict of DateTime -> DateTime, and maps every simulation time to a time present in the forcing dataset.
* Writing some logic to load this dictionary from a file.
* Write the altered functions so that the alternative `get_at` is called for the meteorological forcing, this should happen in `update_forcing`. 

However, `update_forcing!` only takes a single argument (`model`). This could be solved via multiple dispatch, by defining a new model. But you'd still have to change the `update_forcing` function, since it has only four arguments (and so it doesn't have the dict to map from time to time).

There's a simple solution of course: if you include a type into every single function signature, every single function can be overloaded. Currently `get_at` looks like this:

```julia
"Extract a NetCDF variable at a given time"
function get_at(
    ds::CFDataset,
    varname::AbstractString,
    times::AbstractVector{<:TimeType},
    t::TimeType,
)
    # this behaves like a forward fill interpolation
    i = findfirst(>=(t), times)
    t < first(times) && throw(DomainError("time $t before dataset begin $(first(times))"))
    i === nothing && throw(DomainError("time $t after dataset end $(last(times))"))
    return get_at(ds, varname, i)
end
```

Its signature could be changed to e.g.:

```julia
"Extract a NetCDF variable at a given time"
function get_at(
    ::M where M<:AbstractWflowModel,
    ds::CFDataset,
    varname::AbstractString,
    times::AbstractVector{<:TimeType},
    t::TimeType,
)
```

and the call to include `m`. Then @hboisgon could simply write:

```julia
struct ModelHelene{N,L,V,R,W}<: AbstractWflowModel
    config::Config  # all configuration options
    network::N  # connectivity information, directed graph
    lateral::L  # lateral model that holds lateral state, moves along network
    vertical::V  # vertical model that holds vertical state, independent of each other
    clock::Clock  # to keep track of simulation time
    reader::R  # provides the model with dynamic input
    writer::W  # writes model output
    custom_data::Dict{DateTime, DateTime}
end

function get_at
    m::ModelHelene,
    ds::CFDataset,
    varname::AbstractString,
    times::AbstractVector{<:TimeType},
    t::TimeType,
)
    i = findfirst(>=(t), times)
    time = times[i]
    return m.custom_data[time]
end
```

And no changes in `update_forcing!` would be required. You still have to write the logic to load the custom data of course, but you'll have to that anyway. This can be generalized to every single function, at the cost of including an argument that is unused by default.

Of course, this extra type doesn't have to be `Model`, it could be something else specifically defined for overloading purposes, but `Model` doesn't seem so bad at first glance: it's passed around a lot anyway.

**Comment by hboisgon** [comment]
I think that would work yes @verseve !
It also makes sense to update the forcing/cyclic at that level of the code.
In that case I can then write my own custom run/update_forcing/get_at functions
