### ISSUE TITLE
Error with multipath forcing

### ISSUE THREAD

**Issue by hboisgon** [Deltares/Wflow.jl#172]
Hi, 

With @christianli24 we've been trying to use the new functionality for multipath forcing in Wflow (inmaps-*.nc).
However, it seems that the full range of the dates is not properly loaded resulting to this type of errors:
“ERROR: DomainError with time 1991-01-02T00:00:00 after dataset end 1991-01-01T00:00:00”.

The model we are using has daily forcing from 1990-01-01 to 2020-12-31 stored in yearly files (first one 1990-01-01 to 1990-12-31). The model runs fine from 1990 until that date (even for 1991-01-01 which is the first timestep in the second netcdf file). Changing the startdate used in the TOML to a later one (ex 1995),  still gives the same error (the dataset end in the ERROR message is always 1991-01-01).

Attached is the TOML (text version) and full log message
[Wflow.log](https://github.com/Deltares/Wflow.jl/files/7497328/Wflow.log)
[wflow_sbm_test.toml.txt](https://github.com/Deltares/Wflow.jl/files/7497339/wflow_sbm_test.toml.txt)

**Comment by verseve** [comment]
The units of time of each NetCDF file needs to be the same (“days since…”).

**Comment by verseve** [comment]
@hboisgon : is this issue resolved with changing the units of time in the NetCDf files?

**Comment by hboisgon** [comment]
Yes it is! @christianli24 tested it and is now adding it in the "small_things" branch
