### ISSUE TITLE
Flextopo implementation in Julia

### ISSUE THREAD

**Issue by laurenebouaziz** [Deltares/Wflow.jl#178]
I started working on the implementation of flextopo in Julia and I have some questions on the implementation.

As you might know, flextopo is a model which consists of a variable number of classes which are connected with each other through a common groundwater reservoir (see figure with a two classes model here: https://wflow.readthedocs.io/en/latest/wflow_topoflex.html).

Looking at the way SBM is implemented, I thought we could make use of a similar architecture as used for the several soil layers to code the different classes. 

So for example in the staticmaps, we could have for the parameter imax representing the maximum interception capacity a variable imax with dimension "classes" to have an imax map for each class (in a similar way as the c parameter in sbm has a "layer" dimension). However, it does not seem straightforward to implement, as in io.jl ":layer" is in many places hardcoded for reading and handling the netcdf. 

Also it would be great if we could implement svector as is done for ustorelayerdepth of sbm for the various flextopo states and fluxes that are modeled for the three classes, e.g.:
interceptionstorage::Vector{SVector{N,T}} | "mm"
but I am not sure if this is straightforward to implement (I get errors because the method is not implemented, not sure if I am doing something else wrong or if this is just not directly possible). 

thanks and curious to hear your thoughts @visr @verseve!

**Comment by verseve** [comment]
Yes, StaticArrays are fast (as long as we do not have too many classes), so I think it is a good approach to use it for this purpose. 

Indeed, the use of an extra dimension is mostly hard coded now (`layer`), if we want to go for this approach then this requires definitely some changes in io.jl.

**Comment by verseve** [comment]
For StaticArrays a size of 3-5 is perfect. Although `layer` would also work for your implementation, I think it is better to solve this a bit more generic.
