### ISSUE TITLE
Simplified Bagnold parameters

### ISSUE THREAD

**Issue by GuusWW** [Deltares/Wflow.jl#190]
in the Sediment Flux page ( https://deltares.github.io/Wflow.jl/dev/lateral/sediment/ ) there seems to be something odd.
in the paragraph shown in the image it is said that the sp_exp coefficient varies between 1 and 2 usually, while the c_sp coefficient has a wider range of variation. However, looking at the graph below the sp_exp is never found to be between 1 and 2, while the c_sp parameter seems to be between 1 and 2 in many cases. Could it be that these two got swopped?
Thanks!

![image](https://user-images.githubusercontent.com/97171115/148221450-19e504e4-5261-453e-8521-afd242bf4f08.png)

**Comment by hboisgon** [comment]
@GuusWW thanks for your comment.
Indeed in the table the c_sp and sp_exp columns are switched. Will fixed that
