### ISSUE TITLE
Further improve documentation with examples/tutorials and move to Quarto

### ISSUE THREAD

**Issue by JoostBuitink** [Deltares/Wflow.jl#224]
Further improve the documentation. In the current docs, the examples and explanations are somewhat combined, making it difficult for a (new) user to figure out best practices to work with Wflow. It would be nice to separate the examples from the explanations. Additionally, adding some tutorials and/or clear examples would really benefit the usability as well (see [hydromt_wflow docs](https://deltares.github.io/hydromt_wflow/latest/) for a great example).

This would require restructuring of the docs, including new sections. The Documenter.jl package (currently) only supports a menu bar on the left hand side, without different sections such as the hydromt_wflow docs. Adding more sections would make navigating even more difficult (as we are already reaching approaching the limit). Shifting to sphinx would be a solution, but we would lose the direct Julia integration of Documenter.jl: need to figure out the consequences if we want to switch to a different documentation generator.

**Comment by DirkEilander** [comment]
This sphinx-julia package could be something to look in to: https://bastikr.github.io/sphinx-julia/

**Comment by visr** [comment]
Interesting, I hadn't seen sphinx-julia before. For Bach we've been using Quarto and are quite happy with it. The sections or tabs are are configurable. Overall it's quite well designed and documented. The iMOD team was also considering moving to it.

deltares.github.io/Bach.jl/
https://quarto.org/

**Comment by JoostBuitink** [comment]
Also add some text about developer's guide

**Comment by JoostBuitink** [comment]
- [ ] Need some refinement on the actual structure that we will use
- [ ] Discuss with Ribasim team how to setup GitHub actions
- [ ] Copy version switcher from Delft-FIAT
- [ ] Decide whether we still want to link to the current/older docs
