### ISSUE TITLE
ERROR: unsupported cyclic timeseries when running the wflow model in Julia language

### ISSUE THREAD

**Issue by arsalansaghir1** [Deltares/Wflow.jl#247]
I prepared the input files required for wflow simulation using hydromt_wflow plugin. I downloaded the data from several data sources and prepared the input files.
But when I run the simulation in Wflow I get the following error (attached below):
### **ERROR: unsupported cyclic timeseries**
![Screenshot 2023-03-09 234006](https://user-images.githubusercontent.com/127018672/224124265-7fe52cc5-ea21-4801-a1a3-dcbb37b84e38.jpg)

Why I'm getting this error?
I'm attaching the log file for both hydromt_wflow and Julia below.
[log.txt](https://github.com/Deltares/Wflow.jl/files/10934946/log.txt)
[hydromt.log](https://github.com/Deltares/Wflow.jl/files/10934947/hydromt.log)

Kindly guide me on how to proceed with this.

**Comment by verseve** [comment]
> Why I'm getting this error?

This is probably caused by the time stamps of your cyclic timeseries. These should be from the same year or have an integer index.

**Comment by arsalansaghir1** [comment]
Can you specify in more detail? my data is of the same year (2022) and It has an integer index.

This is my nc file for LAI.
[modis_lai.zip](https://github.com/Deltares/Wflow.jl/files/10941721/modis_lai.zip)
