### ISSUE TITLE
ERROR: One or more cycles detected in flow graph.

### ISSUE THREAD

**Issue by BastianT22** [Deltares/Wflow.jl#248]
![image](https://user-images.githubusercontent.com/73870327/225069950-8ac95728-0861-4527-a540-74bae225d69c.png)
The flow direction was upscaled from MERIT-Hydro by PyFlwDir package. But it still reported the error. How can I check the flow direction data? Thank you!

**Comment by verseve** [comment]
Does the flow direction map contains a pit (value = 5)?

If the map contains a pit, probably the easiest way is to check for cycles with pyflwdir. You can use this function (`core.loop_indices`) to detect cycles:
https://github.com/Deltares/pyflwdir/blob/076783cd979660a6706a1a9840873c8b8fc34f48/pyflwdir/core.py#L236

**Comment by BastianT22** [comment]
Thanks for your reply. I have checked that there are pits and no loop. The reason was finally identified that all pixels within the active pixel of the river must flow to pits (which can be not the same), but not to the boundary.

**Comment by BastianT22** [comment]
Hi! You can use a Python package named PyFlwDir to drive rivers by D8 or LDD flow direction raster. And then you can see the the pixels which flow out of the raster boundary. Revise these pixels to pits D8=0 or LDD=5 manually. If your get high resolution data that has numerous pixels. I suggest that you use a edge detection code to revise all the pixels in the basin boundary into pits.

**Comment by BastianT22** [comment]
Hi! You can use a Python package named PyFlwDir to drive rivers by D8 or LDD flow direction raster. And then you can see the the pixels which flow out of the raster boundary. Revise these pixels to pits D8=0 or LDD=5 manually. If your get high resolution data that has numerous pixels. I suggest that you use a edge detection code to revise all the pixels in the basin boundary into pits.

**Comment by BastianT22** [comment]
Dear Joseph,

Hi! It's nice to see the efforts you made to solve this problem. But my suggestion is unchanged. Please use PyFlwDir to derive streams based on flow direction raster (https://deltares.github.io/pyflwdir/latest/_examples/from_dem.html). This is the most effective way to check the problem. Then you may see there are some streams flow out of the raster boundary. Then revise the raster value that flow out of the boundary into pits.
The error reported by the code means that some pixels flow out of the boundary instead of flowing to a pit. Please pay attention that pits out of the boundary are unavailable.

Best wishes,
Zixuan Tang

**Comment by AquaPore** [comment]
Dear Zixuan Tang,

A great thanks for your kindness. A great thanks for your time, I just have the last question?

I wrote the code by using PyFlwDir (see below) and I still have the same issue with Wflow model.

Q1) I will be ever so gratfull if you could kindly check if I have the correct parameters of **pyflwdir.from_dem**, particulary with the options `max_depth=-1.0, outlets="min" ` (code below)?

Q2) How do you investiagte if there are some streams flowing out of the raster boundary, do I have to performe the check manually/ visually? 

A great thanks for your kindness.

Joseph
        

```Python

import rasterio
import numpy as np
import pyflwdir

def DEM_2_LDD_PYFLWDIR(
    Path_Input_Dem,
    Path_Output_Ldd,
    Ldd_MaxDepth=Ldd_MaxDepth,
    Ldd_RiverDepth=Ldd_RiverDepth,
    NoData=NoData,
    outlets="min",
    River=[],
    Idxs_pit=None
):

    # Read elevation data using rasterio
    with rasterio.open(Path_Input_Dem, "r") as src:
        elevtn = src.read(1)
        nodata = src.nodata
        transform = src.transform
        crs = src.crs
        latlon = src.crs.is_geographic
        prof = src.profile

    # returns FlwDirRaster object
    Ldd_Pyflwdir = pyflwdir.from_dem(
        data=elevtn,
        nodata=src.nodata,
        max_depth=-1.0,
        outlets="min",
        transform=transform,
        latlon=latlon,
    )

    Ldd_Array = Ldd_Pyflwdir.to_array(ftype="ldd")

    # Write to tiff file
    prof.update(dtype=Ldd_Array.dtype, nodata=False)
    with rasterio.open(Path_Output_Ldd, "w", **prof) as src:
        src.write(Ldd_Array, 1)

    return Ldd_Array

```

**Comment by AquaPore** [comment]
Dear Zixuan Tang,

I want to express my deepest gratitude for your help. If I am not mistaken you come from the famous _Institute of Geographic Sciences and Natural Resources Research, Chinese Academy of Sciences University._

I am found a nice tool to visualise LDD [lddcreate](https://svn.oss.deltares.nl/repos/openearthtools/trunk/programs/DRIHM/HBV/bin/hbv/openstreams_2013/software/pcraster/pcraster-4.0.0-beta-20131030_x86-64_lsbcc-4/doc/manual/op_lddcreate.html) for which the fundmentals of pyplfdir is build on.

With kindness,
Joseph A.P. Pollacco

![Image](https://github.com/user-attachments/assets/cc008dbe-96b7-475d-b8a1-91e97a368686)
