### ISSUE TITLE
Merging era5_land and era5_single netcdf files

### ISSUE THREAD

**Issue by abdulrehman565** [Deltares/Wflow.jl#260]
I am taking pressure, kin, kout data from era5_single product
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview

and precipitation and temperature data from era5_land product
https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=overview

The precipitation data works but when hydromt calculates the temp_pet_fn it gives an error (Attached Below)

Is there a way to merge era5_land and era5_single netcdf file so they work correctly?
![WhatsApp_Image_2023-05-02_at_4 51 27_PM](https://github.com/Deltares/Wflow.jl/assets/130044572/94ddd40f-c003-4d3f-8249-24d8f133b61a)

**Comment by JoostBuitink** [comment]
This is a duplicate of https://github.com/Deltares/hydromt/issues/336
