### ISSUE TITLE
Saving total evaporation with SBM

### ISSUE THREAD

**Issue by hboisgon** [Deltares/Wflow.jl#263]
Hi ,
I was trying to do some kind of catchment mass balance with for example total precipitation, evaporation, infiltration, recharge etc.

For total evaporation in the basin, I thought actevap (Total actual evapotranspiration) was the variable for this but in the code, there is: 
actevap = soilevap + transpiration + ae_openw_r + ae_openw_l
So I think the interception component is missing, or if we keep actevap as is, maybe we should create a new variable that also includes it?

Also related, in the docs it says that soilevap is soil evaporation from unsaturated store, but in the code this is actually sat + unsat (soilevapunsat is not saved in sbm struct):
https://github.com/Deltares/Wflow.jl/blob/6f3b26b05e0250ffe5c9dfe6b619ce2b34ce88ea/src/sbm.jl#L850

**Comment by verseve** [comment]
Yes, good point, others have also noticed this and it is a bit confusing. I will change `actevap` to include `interception`. And thanks for spotting that `soilevap` in the docs is not correct, will fix this.
