### ISSUE TITLE
Logging of run time

### ISSUE THREAD

**Issue by TBovenschen** [Deltares/Wflow.jl#271]
As for as I know the total execution time of a run is not logged anywhere (except in the terminal itself where you run it from). Would it be possible to write the total run time to the log at the end of the run?

**Comment by JoostBuitink** [comment]
If you use the latest version of Wflow (v0.6.3) the total runtime is written to the log file at the end of the simulation. You should get something like this:
`[ Info: Simulation duration: 6 minutes, 26 seconds, 188 milliseconds`
