### ISSUE TITLE
Cannot run model when adding inflow q_av at lat lon pair to forcing file

### ISSUE THREAD

**Issue by AlessiaRiveros** [Deltares/Wflow.jl#302]
### Wflow version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have checked that this bug exists on the latest version of Wflow.

### Reproducible Example

I have inverse clipped a model excluding a contiguous upstream lake. I then added the outflow to the forcing file. 
This is what my forcing file looks like:
<xarray.Dataset>
Dimensions:  (time: 6941, lat: 1046, lon: 396)
Coordinates:
  * time     (time) datetime64[ns] 1982-02-01 1982-02-02 ... 2001-02-01
  * lat      (lat) float64 -17.69 -17.68 -17.67 -17.66 ... -9.004 -8.996 -8.988
  * lon      (lon) float64 32.68 32.69 32.7 32.7 ... 35.94 35.95 35.95 35.96
Data variables:
    pet      (time, lat, lon) float32 dask.array<chunksize=(365, 1046, 396), meta=np.ndarray>
    temp     (time, lat, lon) float32 dask.array<chunksize=(365, 1046, 396), meta=np.ndarray>
    precip   (time, lat, lon) float32 dask.array<chunksize=(365, 1046, 396), meta=np.ndarray>
    q_av     (time, lat, lon) float32 dask.array<chunksize=(365, 1046, 396), meta=np.ndarray>
Attributes:
    unit:        mm
    pet_fn:      era5
    pet_method:  debruin

### Current behaviour

This is part of the log.txt file I obtain after trying to run the model:
└ @ Wflow C:\Users\riveros\.julia\environments\dev071\dev\Wflow\src\logging.jl:89
[ Info: Wflow version `v0.7.1`
...
[ Info: Set `vertical.precipitation` using NetCDF variable `precip` as forcing parameter.
[ Info: Set `vertical.temperature` using NetCDF variable `temp` as forcing parameter.
[ Info: Set `vertical.potential_evaporation` using NetCDF variable `pet` as forcing parameter.
[ Info: Set `lateral.river.q_av` using NetCDF variable `q_av` as forcing parameter.
...
 @ Wflow C:\Users\riveros\.julia\environments\dev071\dev\Wflow\src\Wflow.jl:216
┌ Info: Run information
│   model_type = "sbm"
│   starttime = CFTime.DateTimeProlepticGregorian(1982-02-01T00:00:00)
│   Δt = 86400 seconds
│   endtime = CFTime.DateTimeProlepticGregorian(2001-02-01T00:00:00)
└   nthreads() = 4
Debug: Starting timestep.
│   time = CFTime.DateTimeProlepticGregorian(1982-02-02T00:00:00)
│   i = 1
│   now() = 2023-09-08T11:02:56.675
└ @ Wflow C:\Users\riveros\.julia\environments\dev071\dev\Wflow\src\Wflow.jl:229
┌ Error: Wflow simulation failed
│   exception =
│    MethodError: Cannot `convert` an object of type Missing to an object of type Float64
│    Closest candidates are:
│      convert(::Type{T}, !Matched::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
│      convert(::Type{T}, !Matched::AbstractChar) where T<:Number at char.jl:185
│      convert(::Type{T}, !Matched::CartesianIndex{1}) where T<:Number at multidimensional.jl:130

### Desired behaviour

I don't know what is mean with an object of type Missing to an object of type Float64.

**Comment by AlessiaRiveros** [comment]
I did two things:
- set the nan values from the q_av to 0
- verify that the coordinates of the inflow were at a river cell
The model is running now.

**Comment by verseve** [comment]
Hi Allessia, if you want to add an external inflow to the river, it is recommended to set the `inflow` parameter of the river (and not `q_av`, because this is an output and thus not used in the river kinematic wave computation).
