### ISSUE TITLE
BMI get_value and grid type

### ISSUE THREAD

**Issue by verseve** [Deltares/Wflow.jl#304]
### Wflow version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have checked that this bug exists on the latest version of Wflow.

### Reproducible Example

Request of grid type seems wrong for some variables. As an example, for `lateral.subsurface.to_river`: request of grid type is incorrect. With BMI.get_var_grid, grid=2 is returned. However, the Vector that is returned with BMI.get_value has the size of grid=4.

### Current behaviour

BMI.get_value deviates from the BasicModelInterface.jl implementation (`dest` argument is missing).
Grid type for some variables seems wrong (see also Reproducible Example).
BMI.get_value should always return a flattened array, this is not the case for variables with an extra dimension (e.g. `layer`), then a Vector of SVectors is returned.

### Desired behaviour

BMI.get_value should have `dest` as argument.
Grid type should be correct for each variable. This has already been resolved in the zmq_server branch (coupling with OpenDA), but good to include in a separate branch that addresses this issue.
BMI.get_value should always return a flattened array (probably need to make use of get_grid_z).

### Additional Context

These BMI issues were reported during an update of eWaterCycle to support Wflow.jl.

**Comment by BSchilperoort** [comment]
Thanks for tackling these issues.


I have found one more (possible) deviation from BMI in Wflow.jl: `get_var_type` usually returns the type of the elements of the array/vector. 

In the bmi-example-julia this is implemented as:
```julia
repr(eltype(m.temperature))
```
However, in Wflow.jl this is implemented as
```julia
string(typeof(param(model, name)))
```
So instead of `Float64`, the returned string will be `Vector{Float64}`.

**Comment by verseve** [comment]
Thanks for spotting this! 
Yes, this should be `eltype` instead of `typeof` in Wflow.jl.

**Comment by verseve** [comment]
I think we need to decide what model grids we want to expose through BMI, with the following two options:

1.  We expose the internal Wflow model variables as unstructured grids (implementation so far). This means we have a 1 to 1 mapping of internal variables to BMI variables. For example, most variables are stored on a uniform rectilinear grid, but internally we store only the active cells (e.g. catchment, river, reservoir or lake cells), and thus for a wflow_sbm model with lakes and reservoirs it is required to define 4 different model grids (different sizes and x, y coordinates). The advantage of this approach is that it is memory efficient, and a conversion (BMI <-> Wflow) is not required (fast). The disadvantage is that we have to define quite some different model grids and that any change of internal Wflow variables has (most probably) a direct effect on the BMI implementation.
2.   We map the internal Wflow variables to Wflow model grids, and then expose through BMI. We already do this for the gridded netcdf output. In the most simple case we only define 1 grid type (uniform rectilinear), with keeping in mind that for some variables (local inertial model) these are actually stored on edges (unstructured grid). Or we add also explicit grid types for the local inertial model with node and edge information (could even do this also for the kinematic wave (variables are mapped here only to nodes)).

Finally, some variables in Wflow have an extra (3rd) dimension, for example `classes` for `flextopo` and `layer` for `sbm` (internally these are stored as a Vector of SVectors. I suggest we expose these variables as 2D (and not 3D) through BMI, and could do this in the same way as the wflow Python version (with adding an underscore and index to the variable name, e.g.: `vertical.vwc_1`).

**Comment by visr** [comment]
I'm a bit torn on this. My first thought was that the grids need to be unstructured to have a 1:1 mapping for performance reasons. Though from a usability perspective unstructured is really quite a bit more difficult, and as you say in our output files we also act like it is a 2D model. The BMI grid implementation is just not so well suited for what we do internally. It is a structured grid, we just don't store it as such internally.

I suggest we go for option 2. I think copying data from 1D internal to 2D BMI is not too costly if we do that for every timestep, provided we re-use the 2D memory. We can measure it first to be sure.

> I suggest we expose these variables as 2D (and not 3D) through BMI

Is that assuming picking option 2? And "1D (and not 2D)" for option 1? Why do you prefer this? If we go for option 2, I think offering 3D grids to BMI here is the most obvious choice.

**Comment by visr** [comment]
> Arrays are always flattened in BMI. A user always needs to convert the data (1D Array) to a 2D Array if this is required, for both option 1 and 2.

I read about flattening in the BMI best practices, and actually I don't really understand it, at least in the context of Julia. I wrote about it in [these notes](https://github.com/Deltares/BasicModelInterface.jl/?tab=readme-ov-file#notes-and-open-questions) starting from the best practices quote. If flattening is just a reshape/reinterpretation of the same memory, how does flattening a vector avoid row/column major confusion? And in a julia-to-julia BasicModelInterface, I don't see any benefit in flattening, it just destroys the true shape information, but is otherwise functionally the same, especially with Julia's linear indexing into multi dimensional arrays. So in the [bmi-example-julia](https://github.com/csdms/bmi-example-julia) I just returned a Matrix, since I didn't see the point in calling `vec(a)` first. I could be missing something there though, then we should update it.

@BSchilperoort maybe you also have some ideas on this, since you also mentioned a flat vector should be returned by `BMI.get_value`. Would be good to address these open questions from the BasicModelInterface.jl README.md.

**Comment by BSchilperoort** [comment]
> @BSchilperoort maybe you also have some ideas on this, since you also mentioned a flat vector should be returned by BMI.get_value.

The main reason I care about that, is that this is the BMI specification. Exactly following the specification allows others to write code that should work on any model implementing a BMI (e.g. eWaterCycle and grpc4bmi).

For example, in eWaterCycle we have a routine "get_value_as_xarray" which wraps the BMI functions and returns the data in an xarray DataArray. This only works if there is a standard across languages.

>  in a julia-to-julia BasicModelInterface, I don't see any benefit in flattening, it just destroys the true shape information, but is otherwise functionally the same, especially with Julia's linear indexing into multi dimensional arrays. 

Yes, for these cases it's often a hassle to flatten. Same with for example the _dest_ argument being required: this doesn't really make sense for languages such as Python or Julia.
However, not all languages work the same and BMI can also be used to couple across languages.

> So in the [bmi-example-julia](https://github.com/csdms/bmi-example-julia) I just returned a Matrix, since I didn't see the point in calling vec(a) first. I could be missing something there though, then we should update it.

I had not noticed that yet, but that should then be updated, yes.

> In addition, a possible risk with option 1 is that we end up with many different grid types over time, when more variables are added to Wflow.

In my opinion fewer grid types would be better, as I think it will get confusing to users of the BMI quite fast.

**Comment by visr** [comment]
Ok yes I was struggling to come up with an example in Julia where the Vector/Matrix difference matters, but when PythonCall.jl converts a Matrix to a 2D numpy array then indeed that can cause issues. Updated the example in https://github.com/csdms/bmi-example-julia/pull/5.

**Comment by verseve** [comment]
Ok, but for the BMI uniform rectilinear grid type, you need to know if the flattened array is from a row or column major language (the node location functions are not listed as part of the uniform rectilinear grids)? Or am I missing something?

**Comment by visr** [comment]
Yes this part is also not that clear to me yet. The BMI best practices state.

> It’s the developer’s responsibility to ensure that array information is flattened/redimensionalized in the correct order.

The summary table states what dimensions 1, 2 and 3 should be. If that needs to be true for both row and column-major languages, the data needs to be permuted, which is expensive. If say we want to write to GeoTIFF from Julia we often use (y,x) rather than (x,y) such that the row-major interpretation of that is (x,y) again.

<html>
<body>


Function | Description
-- | --
get_grid_x | Get the locations of a grid’s nodes in dimension 1.
get_grid_y | Get the locations of a grid’s nodes in dimension 2.
get_grid_z | Get the locations of a grid’s nodes in dimension 3.


</body>
</html>

**Comment by BSchilperoort** [comment]
> Ok, but for the BMI uniform rectilinear grid type, you need to know if the flattened array is from a row or column major language (the node location functions are not listed as part of the uniform rectilinear grids)? Or am I missing something?

As far as I can see, this is sadly not specified (yet). There is a discussion about this topic here: https://github.com/csdms/bmi/issues/118

**Comment by verseve** [comment]
After reading through issue https://github.com/csdms/bmi/issues/118, I am leaning to use unstructured grid types in Wflow for now, at least until this issue has been resolved. I agree that this grid type can be more difficult from a user perspective, on the other hand a student was able to couple Modflow 6 and Wflow without too many issues a couple of years ago. As indeed fewer grid types would be better, I think we need only two grid types:

1. Unstructured grid at catchment scale.
2. Unstructured grid for river flow (local inertial model).

**Comment by verseve** [comment]
Although fewer grid types would be better from a user perspective, at the moment it does not seem worth to support this with the use of a buffer (@visr and I concluded this after a brief discussion). For example. to support reservoirs as part of a river grid type, a reference (for example with `Base.Ref`) within the buffer to the reservoir variables is required (BMI function `get_value_ptr`), or an index mapping between the buffer and reservoir variables for `set_value` and `set_value_at_indices` is required (in that case the buffer does not contain references, but this is probably not a valid implementation of `get_value_ptr`). 

For the use of fewer grid types it makes more sense to solve this at the `Model` level directly, and not partly in the BMI layer and partly in Wflow. This can be part of another issue/PR.

**Comment by verseve** [comment]
Hi Bart (@BSchilperoort), do the code changes in branch [BMI](https://github.com/Deltares/Wflow.jl/tree/BMI) now work for fine for eWaterCycle (Albrecht got the impression it is working now during a workshop with escience this week)? The branch will also go through an internal code review, but would be good to also have some feedback from your side.

**Comment by BSchilperoort** [comment]
Hi Willem, as far as I know the BMI is now complete and compliant with BMI 2.0. It worked great during the workshop. Thank you for implementing these fixes! If we encounter anything else at some point we'll open up an issue.

The only thing not working yet for eWaterCycle is putting the model in a container and communicating with it through gRPC, as a Julia native implementation of a gRPC server does not exist. Trying to pass the BMI through Python or C has led to segfaults and other issues. We'll still have to work on this, and possibly use a different communication protocol. However, this is not related to this PR or any code in Wflow.jl.
