### ISSUE TITLE
Support for `CFTime.DateTimeNoLeap` calendar

### ISSUE THREAD

**Issue by BSchilperoort** [Deltares/Wflow.jl#308]
### Feature type

Changing existing functionality

### Improvement Description

The current supported calendar types of forcing data seem to be `CFTime.DateTimeJulian, CFTime.DateTimeProlepticGregorian, CFTime.DateTimeStandard`. However, the `CFTime.DateTimeNoLeap` calendar is not supported. 

Many global climate models use this "noleap" calendar, so it would be nice to be able to use the data from those without a tricky conversion.

On [this line](https://github.com/Deltares/Wflow.jl/blob/ac78c329da9a050905b1024d87f067961fee342f/src/io.jl#L268) the following error is raised:
```jl
JuliaError: MethodError: Cannot `convert` an object of type CFTime.DateTimeNoLeap to an object of type Dates.DateTime

Closest candidates are:
  convert(::Type{Dates.DateTime}, !Matched::T2) where T2<:Union{CFTime.DateTimeJulian, CFTime.DateTimeProlepticGregorian, CFTime.DateTimeStandard}
```

### Additional Context

I encountered this issue while trying to generate forcing data for Wflow.jl with eWaterCycle + ESMValTool.

**Comment by JoostBuitink** [comment]
We actually do support using different calendar types (all CF convention calendars), and have run Wflow with different types of calendars. However, in order to make sure this works, you need to specify the calendar type in your toml file. See [this page](https://deltares.github.io/Wflow.jl/dev/user_guide/step2_settings_file/#General-time-info) in the documentation for some additional explanations.

In your case, it should be `calendar = "noleap"` or `calendar = "365_day"`. See this page for the different calendar options: https://cfconventions.org/cf-conventions/cf-conventions.html#calendar

Hopefully this solves your issue!

**Comment by BSchilperoort** [comment]
Hi Joost, thanks for your reply. I have actually set the calendar to "noleap" already in the config file, however it does not work.
Setting it to "365_day" produces the exact same error as I outlined in the first post.

Here's the start of the config file:
```toml
casename = "wflow_sbm"
calendar = "noleap"
starttime = "1990-01-01T00:00:00"
endtime = "1990-12-31T00:00:00"
time_units = "days since 1900-01-01 00:00:00"
timestepsecs = 86400
```

**Comment by BSchilperoort** [comment]
Looking at the [`CFTime.jl`](https://juliageo.org/CFTime.jl/latest/) package, the `convert` function is quite limited in the calendar types it accepts.

To be able to convert from a noleap calendar, the [`reinterpret`](https://juliageo.org/CFTime.jl/latest/#Base.reinterpret) function has to be used.

**Comment by JoostBuitink** [comment]
And how is the time dimension setup in your forcing file? I have ran Wflow in the past with 365_day (and 360_day) calendar without issue. The time dimension in my forcing dataset looks like this (opened with xarray):

```
array([cftime.DatetimeNoLeap(1970, 1, 1, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1970, 1, 2, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(1970, 1, 3, 0, 0, 0, 0, has_year_zero=True), ...,
       cftime.DatetimeNoLeap(2014, 12, 29, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 12, 30, 0, 0, 0, 0, has_year_zero=True),
       cftime.DatetimeNoLeap(2014, 12, 31, 0, 0, 0, 0, has_year_zero=True)],
      dtype=object)
```

**Comment by BSchilperoort** [comment]
What it looks like in xarray depends a bit on which packages you have installed
This is the info from `ncdump`

<pre>	double time(time) ;
		time:axis = &quot;T&quot; ;
		time:bounds = &quot;time_bnds&quot; ;
		time:units = &quot;days since 1850-1-1 00:00:00&quot; ;
		time:standard_name = &quot;time&quot; ;
		time:long_name = &quot;time&quot; ;
		time:calendar = &quot;365_day&quot; ;
		time:calendar_type = &quot;noleap&quot; ;
		time:cartesian_axis = &quot;T&quot; ;
</pre>

The data has been generated using ESMValTool, so it should adhere to the CF-1.7 and CMOR standards

<hr>

If I change the following line 
https://github.com/Deltares/Wflow.jl/blob/ac78c329da9a050905b1024d87f067961fee342f/src/io.jl#L268

to:

```jl
        time = reinterpret(eltype(dataset_times), clock.time)
```
the model runs fine with the noleap calendar.

**Comment by BSchilperoort** [comment]
Hi Willem. I have been trying to reproduce the error however I am not encountering it anymore...

I am now able to provide the model with a noleap calendar, and run it without any issues. I'll close this issue now, if I encounter the error again I will reopen it. Thanks!
