### ISSUE TITLE
Re-infiltration of Surface Water

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/Wflow.jl#349]
### Feature type

Adding new functionality

### Improvement Description

The current model lacks the capability to simulate the re-infiltration of surface water into the subsurface, which is a crucial process in hydrological modeling, especially in scenarios involving rainfall-runoff dynamics and groundwater recharge.

### Implementation Description

Implement Re-infiltration Mechanism: Introduce a re-infiltration mechanism to simulate the process of surface water returning to the subsurface after runoff events. This enhancement will improve the accuracy of the model by accounting for the complex interactions between surface water and groundwater, ultimately leading to more realistic hydrological simulations.

**Comment by verseve** [comment]
Issue already reported https://github.com/Deltares/Wflow.jl/issues/237.
