### ISSUE TITLE
Unicode Character Usage and Consistency

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/Wflow.jl#352]
### Feature type

Changing existing functionality

### Improvement Description

The current codebase utilizes Unicode characters inconsistently. The advantage of Unicode characters is that the implementation remains close to the model equations, making the code more readable and easier to understand (improving maintainability of the code). In addition, to make fully use of Unicode characters, these characters should also be included in the documentation (code notation matches notation in documentation).  Possible disadvantages of using Unicode characters are: more difficult to type, searching (example is required) and editor or text processor could have problems correctly displaying these characters (config TOML file). It's essential to evaluate the usage of Unicode characters, considering their advantages and disadvantages, and ensure consistent usage throughout the codebase.

### Implementation Description

Make a well considered choice (use consistent or not) and refactor the code (and change docs) based on the choice.

**Comment by JoostBuitink** [comment]
We have decided to stop using unicode characters, and spell them out if necessary (for example `theta_s` instead of the Greek symbol). We aim for the variables to be as descriptive as possible, while ensuring the names won't get too long as that could limit readability of the code
