### ISSUE TITLE
Wflow ZMQ Server: `BMI.getvalue` can throw JSON spec error

### ISSUE THREAD

**Issue by verseve** [Deltares/Wflow.jl#392]
### Wflow version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have checked that this bug exists on the latest version of Wflow.

### Reproducible Example

Requesting wflow variables with the default `ksat_profile` setting through the wflow ZMQ Server. 

### Current behaviour

The following error is thrown:

┌ Error: Wflow function `get_value` failed
│   exception =
│    NaN not allowed to be written in JSON spec
│    Stacktrace:
│      [1] error(s::String)
│        @ Base .\error.jl:35
│      [2] #write#90

### Desired behaviour

In this case the model variables `vertical.z_layered` and `lateral.subsurface.kh` are set at NaN during initialization of a wflow model with the default `ksat_profile` setting. Preferably we do not allow to exchange NaN with JSON because it is not standard.

**Comment by vers-w** [comment]
JSON3 allows for reading and writing of `NaN` and `Inf` values, through the keyword arg `allow_inf`. A similar option is available in the Java library used in OpenDA for data assimilation with wflow.
