### ISSUE TITLE
Editorial changes on user_guide/intro.md

### ISSUE THREAD

**Issue by petershintech** [Deltares/Wflow.jl#457]
### Wflow version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `master` [here](https://github.com/Deltares/Wflow.jl)

### Kind of issue

Docs are unclear

### Location of the documentation

docs/src/user_guide/intro.md

### Documentation problem

Some editorial improvement is required.

### Suggested fix for documentation

Please find the PR related.

**Comment by Shadi201711** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
