### ISSUE TITLE
documentation: paragraph repeated twice

### ISSUE THREAD

**Issue by laurenebouaziz** [Deltares/Wflow.jl#53]
This paragraph in the documentation is repeated twice:

**Transpiration and soil evaporation**

_The potential eveporation left over after interception and open water evaporation (rivers and water bodies) is split in potential soil evaporation and potential transpiration based on the canopy gap fraction (assumed to be identical to the amount of bare soil)._

**Comment by visr** [comment]
Good catch! Can I invite you to make the edit here https://github.com/Deltares/Wflow.jl/edit/master/docs/src/vertical/sbm.md and submit a pull request? Otherwise I can get to it myself later.

**Comment by laurenebouaziz** [comment]
sure!
