### ISSUE TITLE
OpenDA coupling

### ISSUE THREAD

**Issue by visr** [Deltares/Wflow.jl#93]
~~This will likely need BMI 2.0 support in OpenDA first.~~
We will probably do this using the black box model approach, using the `wflow_cli`.

**Comment by verseve** [comment]
Started with OpenDA memory coupling approach with Thrift.jl (black box model approach is too slow). It seems the handling of user-defined exceptions is not working properly, with Thrift-0.8.4 an error is thrown immediately, and with Thrift-0.7.1 an error is thrown when the user-defined exception occurs, see also the following issue https://github.com/tanmaykm/Thrift.jl/issues/76.

**Comment by verseve** [comment]
After discussion (also with OpenDA developers) we decided to use ZeroMQ (https://zeromq.org/) instead of Thrift to run Wflow (BMI) as a server  for the coupling approach.

**Comment by visr** [comment]
Work in progress in the `zmq_server` branch: https://github.com/Deltares/Wflow.jl/tree/zmq_server
What is the status of this branch?

**Comment by verseve** [comment]
> Work in progress in the `zmq_server` branch: https://github.com/Deltares/Wflow.jl/tree/zmq_server What is the status of this branch?

Changes on the OpenDA side are in progress. When done, the work in the `zmq_server` branch can be finished.
