### ISSUE TITLE
model parameters in CSV or TOML

### ISSUE THREAD

**Issue by verseve** [Deltares/Wflow.jl#99]
Model parameters should be provided in NetCDF format. For some parameters it would make sense to have the option to provide these parameters in CSV format or as part of the TOML file:

- reservoir parameters (CSV)
- lake parameters (CSV)
- gauges (CSV)
- parameters that don't vary in space (TOML), e.g. "input.vertical.khfrac"

**Comment by Huite** [comment]
Just some drive-by thoughts, does it really make sense to add support for CSV?

* CSV does not have a formal specification, generally quite a lot of issues with delimiters, quoting behavior, etc.
* Tab-separated (TSV) is somewhat better
* netCDF4 is clearly general enough (N-dimensional) to store tabular data (2D)
* Also has clear encoding rules for e.g. datetimes (while text-based dates do not: yyyymmdd; yyyy-mm-dd; yyyy/mm/dd; and all the permutations)

If the goal is to allow easier editing, I'd indeed argue that for input of tables, excel is good. Being able to quickly plot a level or gauge via excel (which I think is the main tool you'd reach with this) is also quite convenient. However, I'd argue that place for this should probably be an external conversion tool.

**Comment by verseve** [comment]
Yes, the main goal is to allow for easier editing by users (instead of manipulating the NetCDF file with model parameters directly). We support at the moment some CSV reading through [readdlm](https://docs.julialang.org/en/v1/stdlib/DelimitedFiles/), for files that contain lake information, like a storage-height relationship.

I agree, we should consider this kind of support carefully, and as you just mentioned to me we could also explore "NetCDF editing", for example in QGIS.

**Comment by abdulrehman565** [comment]
Is there a way to provide gauges coordinates directly in the toml file?
I'm using hydromt to add multiple gauges points using a csv file but hydromt takes a lot of time to prepare input files. I was wondering if I could change gauges coordinates directly in the toml?

**Comment by visr** [comment]
@abdulrehman565 yes you can enter coordinates directly in the TOML file. The documentation for this is here: https://deltares.github.io/Wflow.jl/dev/user_guide/step2_settings_file/#Output-CSV-section

```TOML
[[csv.column]]
coordinate.x = 6.255
coordinate.y = 50.012
header = "temp_bycoord"
parameter = "vertical.temperature"
```

**Comment by mullerrobert799** [comment]
I'd like to print flows for each grid cell. Is there any way to do that?
